workload_template: 'cfg_icni1_f5_node_density.yml'
scale_factor: 2
bfd_enabled: false
uuid: 'poiy761b-d12e-4922-86a2-ea17354d80hh'
es_server: 'https://search-perfscale-dev-chmf5l4sh66lvxbnadi4bznl3a.us-west-2.es.amazonaws.com:443'
es_index: 'ripsaw-kube-burner'
kubeconfig: |
  apiVersion: v1
  clusters:
  - cluster:
      certificate-authority-data: LS0tLS1CR...
      server: https://api.dummycluster.openshift.com:6443
    name: api-dummycluster-openshift-com:6443
